{% set name = "bpython" %}
{% set version = "0.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fec7d97be9912a50d8f5b34ca10d70715c99a33f0cd0b9e4977c1b0f617fa913

build:
  number: 1
  entry_points:
    - bpython = bpython.curtsies:main
    - bpython-curses = bpython.cli:main
    - bpython-urwid = bpython.urwid:main
    - bpdb = bpdb:main
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py2k]
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
  run:
    - curtsies >=0.1.18
    - greenlet
    - pygments
    - python
    - requests
    - six >=1.5
    - urwid  # [unix]
    - watchdog

test:
  imports:
    - bpdb
    - bpython
    - bpython.curtsiesfrontend
    - bpython.test
    - bpython.test.fodder
    - bpython.translations
  commands:
    - bpython --help
    - bpython-curses --help
    - bpython-urwid --help
    - bpdb --help

about:
  home: http://www.bpython-interpreter.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fancy Interface to the Python Interpreter
  dev_url: https://github.com/bpython/bpython

extra:
  recipe-maintainers:
    - mariusvniekerk
    - scopatz
